/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.util.*;

import org.example.struct.Tree;


public class App {
    

    public static void main(String[] args) {
        var tree = new Tree<>(new File("/home"));
        tree.insert(new File("/home/luispazos"));

        
        for(var itr = tree.iterator(); itr.hasNext();){
            File file = itr.next();

            System.out.println(file.getName());
        }

        File[] list = tree.root.value.listFiles();
        for (File data : list) {
            System.out.println(data + " isdirectory? " + data.isDirectory());
        }
    }
}

/* FileOrganizer root = new FileOrganizer("/home/luispazos/Descargas/");
        System.out.println(root.getRoot().getAbsolutePath());
        System.out.println(root.getRoot().exists());
        
        File[] list = root.getRoot().listFiles();

        for (File data : list) {
            System.out.println(data + "isdirectory?" + data.isDirectory());

        } */
